### ISSUE TITLE
Working with foreign characters

### ISSUE THREAD

**Issue by CarlosJimenez** [kbirgoren/sketch-json-translator#5]
I think your plugin is excellent

I was trying to use to translate 20 languages.
I have found issues with a few foreign characters, I imagine the same issue when I include chinese, korean, japanese...

I copied a JSON with 4 languages that includes accented vowels.

I am using json coded in utf-8

[iPhone X Wifi Settings.json.zip](https://github.com/kbirgoren/sketch-json-translator/files/3284557/iPhone.X.Wifi.Settings.json.zip)

What I am doing wrong?

Best regards

**Comment by kbirgoren** [comment]
Hello @CarlosJimenez, I did not test it with foreign characters to be honest. It's a nice catch thanks for reporting. I am going to check this and let you know.

**Comment by kbirgoren** [comment]
@CarlosJimenez It is solved now. Please check latest version on https://github.com/kbirgoren/sketch-json-translator/releases/tag/1.2
