### ISSUE TITLE
Support separate translation files per language

### ISSUE THREAD

**Issue by ziyafenn** [kbirgoren/sketch-json-translator#6]
Hello and thanks for an amazing plugin.

Unfortunately, my coding knowledge is very limited otherwise i would just add the fork myself. But, is there any possibility to use separate JSON files per language? As project i'm working on is very large and it hard to maintain the translation in one single file, as currently your plugin is structured.

Thanks!

**Comment by kbirgoren** [comment]
Hi @ziyafenn, if it's in correct format you can upload different language file each time you want to translate.

So instead of 

`{
  "en": {
    "page1": {
      "hello": "Hello English",
      "bye": "Good bye English!"
    }
  },
  "nl": {
    "page1": {
      "hello": "Hello Dutch",
      "bye": "Good Bye Dutch!"
    }
  },
  "de": {
    "page1": {
      "hello": "Hello German",
      "bye": "Good Bye German!"
    }
  }
}`

You can have 3 different file like

`{
  "en": {
    "page1": {
      "hello": "Hello English",
      "bye": "Good bye English!"
    }
  }
}`


`{
  "de": {
    "page1": {
      "hello": "Hello German",
      "bye": "Good bye German!"
    }
  }
}`


`{
  "nl": {
    "page1": {
      "hello": "Hello Dutch",
      "bye": "Good bye Dutch!"
    }
  }
}`

**Comment by ziyafenn** [comment]
hey @kbirgoren i just tried your proposed solution and unfortunately, it didn't work.

I created two separate files and uploaded first the english version, everything worked fine.

Then i uploaded second file (de) and when i go to the `Update All Texts`, in menu i still see the `EN` version and when i update the text, i get no translation but rather an error in my text layers (see screenshot). 

Thanks.
![Screenshot 2019-10-01 at 13 19 20](https://user-images.githubusercontent.com/314302/65959197-a7c99280-e451-11e9-925c-6f819d3f0139.png)

**Comment by kbirgoren** [comment]
You should always upload a file and then select the language to use separate files.

**Comment by ziyafenn** [comment]
Yep, i upload files each time before updating strings as i described in the previous post. Still getting error.
