### ISSUE TITLE
Use variables as a text and not layer names

### ISSUE THREAD

**Issue by ziyafenn** [kbirgoren/sketch-json-translator#7]
Another subject that i was curious, if it is at all possible to use the variables inside text layers and not as a layer names?

The only reason why i'm asking is that having variables as a layer name makes them unreadable and especially when exporting to an external service, such as Invision, is very hard to navigate through them. 

And when managing a symbol, it gets even crazier.

Thanks in advance!

**Comment by kbirgoren** [comment]
Hi @ziyafenn, it is not possible to use variables in text layers since the script is overwriting the text value in a text layer. It is not really possible to find a better solution for that.
