### ISSUE TITLE
After updating text layers, symbols do not resize automatically

### ISSUE THREAD

**Issue by ziyafenn** [kbirgoren/sketch-json-translator#8]
I encounter a problem when i use this plugin with my symbols in Sketch 58. 

Each time after updating the translation, in Sketch 58 Smart layout feature does not get triggered automatically as it does usually.

So if i have a button label in eng that is much shorter than the german version, after using the translation update to german, the button does not resize itself. But rather i have to do it manually using a specific button in sidebar (shrink to fit).

It is good enough when there are not that many symbols, but it gets more complicated when there are plenty of symbols on the artboard and each of them has to be updated manually.

**Comment by kbirgoren** [comment]
Hi @ziyafenn , I did not check the plugin with Sketch 58. I am so busy with other things recently I think I need to add support for that. I will do a new release when I have time.
